### ISSUE TITLE
NamespacedKeyArgument does not work in 1.17

### ISSUE THREAD

**Issue by BeefDev** [JorelAli/CommandAPI#323]
### CommandAPI version

8.5.0

### Minecraft version

1.17

### Are you shading the CommandAPI?

Yes

### What I did

Register this command
```java
private CommandAPICommand nameSpacedKeyCommand() {
        return new CommandAPICommand("printkey")
            .withArguments(new NamespacedKeyArgument("key"))
            .executesPlayer((player, arguments) -> {
                  NamespacedKey key = (NamespacedKey) arguments[0];

                  player.sendMessage(ChatColor.RED + "Namespace: " + ChatColor.YELLOW + key.getNamespace());
                  player.sendMessage(ChatColor.RED + "Key: " + ChatColor.YELLOW + key.getKey());
        });
}
```

Run the command `/printkey mynamespaced:mykey`

### What actually happened

[A NoSuchMethodError was thrown](https://pastebin.com/A52rSJAe)
(Speciffically the error happens on `commandapi.nms.NMS_Common.getMinecraftKey(NMS_Common.java:416)`, because there is no 
```
MinecraftKey ArgumentMinecraftKeyRegistered.e(CommandContext, String)
```
method.

### What should have happened

The command executes normally, and the namespace & key are sent to the player as messages

### Server logs and CommandAPI config

Don't think it will be much of a use, but here:

on load
```
[11:55:27 INFO]: [CommandAPI] Hooked into NMS io.github.beefdev.commandapireports.dependencies.commandapi.nms.NMS_1_17_R1 (compatible with 1.17.1)
[11:55:27 WARN]: [CommandAPI] Could not hook into the NBT API for NBT support. Download it from https://www.spigotmc.org/resources/nbt-api.7939/
[11:55:27 INFO]: [CommandAPI] Hooked into Spigot successfully for Chat/ChatComponents
[11:55:27 INFO]: [CommandAPI] Hooked into Adventure for AdventureChat/AdventureChatComponents
[11:55:27 INFO]: [CommandAPI] Hooked into Paper for paper-specific API implementations
```

on enable
```
[11:55:36 INFO]: [CommandAPI] Registering command /printkey key<NamespacedKeyArgument>
...
[11:55:39 INFO]: [CommandAPI] Linking permissions to commands:
[11:55:39 INFO]: [CommandAPI] NONE -> /printkey
[11:55:39 INFO]: [CommandAPI] Linked 1 Bukkit permissions to commands
[11:55:39 INFO]: [CommandAPI] Reloading datapacks...
```

**Comment by willkroboth** [comment]
This looks similar to the problem solved by #304, where the data packs reload failed on a 1.17 server due to special source mapping a field to slightly different values between 1.17 and 1.17.1. Luckily the framework for splitting 1.17 and 1.17.1 NMS is already in place thanks to that PR, so this should be fixed easily.

**Comment by BeefDev** [comment]
> This looks similar to the problem solved by #304, where the data packs reload failed on a 1.17 server due to special source mapping a field to slightly different values between 1.17 and 1.17.1. Luckily the framework for splitting 1.17 and 1.17.1 NMS is already in place thanks to that PR, so this should be fixed easily.

Ok, thanks for informing me

**Comment by JorelAli** [comment]
Implemented in e12b07d830759907aa0b7e5fd314ba29800ad705 for 8.5.1.
